### ISSUE TITLE
[Issue/all] 임시 대응 내역 및 리팩토링 필요 목록 (코드 기반 명세 포함)

### ISSUE THREAD

**Issue by lunghyun** [100-hours-a-week/14-YG-CLOUD#34]
현재 `test` 서버 기준으로 운영되는 구조는 여러 환경을 동시에 대응하기 위한 **임시 구조 및 강제 삽입 로직**이 포함되어 있으며, 이후 운영 전환 또는 구조 고도화 시 반드시 리팩토링이 필요합니다.

---

## ✅ 백엔드(Spring) - CORS 설정 강제 삽입

- 위치: `SecurityConfig.java`
- 적용 방식: **Ansible `lineinfile`**
  ```yaml
  - name: Ensure CORS allows dev/test domains
    lineinfile:
      path: /home/ubuntu/14-YG-BE/src/main/java/com/moogsan/moongsan_backend/global/config/SecurityConfig.java
      insertafter: '^\s*config\.setAllowedOrigins\(List\.of\($'
      line: '                "https://{{ nginx.domain }}",'
      state: present
  ```
- 한계:
  - Git 충돌 가능성
  - 운영 전환 시 환경 변수 기반 전환 필요
- 리팩토링 제안:
  - application.yml 또는 환경 변수 기반 CORS 설정 분리

---

## ✅ 프론트 - `.env` 및 Vite 설정 템플릿화

- 파일:
  - `.env` 생성: `vite.env.j2`
  - `vite.config.ts`: 템플릿으로 프록시 설정 주입
- 적용 방식: **Ansible `template:`**
  ```dotenv
  VITE_BASE_URL="https://{{ nginx.domain }}"
  ```
  ```ts
  proxy: {
    "/api": {
      target: "{{ vite_proxy_target }}",
      changeOrigin: true,
      secure: false,
    }
  }
  ```
- 리팩토링 제안:
  - CI 단계에서 `.env` 자동 주입
  - 운영 환경에서는 정적 proxy 제거

---

## ✅ nginx - CORS 헤더 수동 삽입

- 파일: `nginx_https_default.j2`
- 위치: `/api/` 블록 내
  ```nginx
  add_header Access-Control-Allow-Origin "https://{{ nginx.domain }}";
  add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE, PATCH";
  add_header Access-Control-Allow-Headers "*";
  ```
- 리팩토링 제안:
  - Spring Security에서 CORS 관리 통합
  - nginx는 reverse proxy 전용으로 단순화

---

## ✅ Dockerfile 복사 및 소스 내 빌드 (BE/FE)

- 적용 방식: **Ansible `copy:`**
  ```yaml
  - name: Copy Dockerfile to BE/FE repo for build
    copy:
      src: /home/ubuntu/14-YG-CLOUD/docker/backend/Dockerfile
      dest: /home/ubuntu/14-YG-BE/Dockerfile
      remote_src: true
  ```
- 리팩토링 제안:
  - GitHub Actions에서 build & push
  - 서버는 `pull + run` 방식으로 단순화

---

## ✅ AI 서비스 - requirements.txt 조작

- 적용 방식: **Ansible `lineinfile`로 강제 추가 및 수정**
- 파일: `/home/ubuntu/14-YG-AI/requirements.txt`
- 삽입/수정된 내용:
  ```ini
  PyYAML>=6.0
  torch==2.3.0
  opencv-python-headless==4.9.0.80
  pytest-mock==3.14.0
  uvicorn[standard]
  ```
- 목적:
  - easyocr, langgraph 등과의 의존성 충돌 방지
  - 테스트 환경 고정
- 관련 Ansible 태스크 예시:
  ```yaml
  - name: Ensure torch==2.3.0 is present
    lineinfile:
      path: /home/ubuntu/14-YG-AI/requirements.txt
      regexp: "^torch"
      line: "torch==2.3.0"
      insertafter: EOF
  ```
- 리팩토링 제안:
  - requirements.txt 자체 수정 후 repo에 반영
  - 테스트/운영 환경에 따라 별도 requirements 분리 (e.g. `requirements.prod.txt`)

---

## 🧩 통합 리팩토링 방향 정리

| 항목                  | 현재 상태                   | 개선 제안                         |
|-----------------------|-----------------------------|-----------------------------------|
| CORS 설정             | Java 코드에 직접 삽입       | 환경 변수 또는 YAML 분리          |
| 프론트 `.env`         | Ansible 템플릿 생성         | CI 단계에서 주입                  |
| vite.config 프록시     | 템플릿으로 환경 주입        | 운영 환경에서는 제거              |
| nginx CORS 헤더       | 템플릿에 직접 삽입          | Spring에서 일괄 관리              |
| Dockerfile 복사       | Ansible에서 수동 복사       | GitHub Actions build/push로 전환  |
| AI requirements       | Ansible로 조작              | 레포지토리 자체 수정              |

---

> ✳️ 이 문서는 `test` 환경 기준이며, 운영 전환 시 반드시 재정비되어야 할 항목들을 포함합니다.
